# Generated by Django 3.1.3 on 2020-11-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201103_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='boxOffice',
            new_name='boxoffice',
        ),
    ]
