# Generated by Django 3.1.3 on 2020-11-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20201103_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='raitings',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Rating'),
        ),
    ]
