# Generated by Django 3.1.3 on 2020-11-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201103_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='raitings',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movie'),
            preserve_default=False,
        ),
    ]
