# Generated by Django 3.1.3 on 2020-11-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20201104_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='raitings',
            new_name='ratings',
        ),
    ]
